version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: portohost-db
    environment:
      MYSQL_DATABASE: portohostdb
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - portohost-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/portohostdb
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - portohost-network
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - maven_cache:/root/.m2
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - portohost-network

volumes:
  db_data:
  maven_cache:

networks:
  portohost-network:
    driver: bridge