server:
  port: 8080

spring:
  application:
    name: portohost
  datasource:
    url: jdbc:mysql://db:3306/portohostdb
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      properties:
        hibernate:
          show_sql: true
          format_sql: true
    output:
      ansi:
        enabled: Always

logging:
  level:
    com.franciscoabsl: INFO
    root: INFO
    org:
      hibernate: DEBUG
      springframework:
        web: DEBUG