server:
  port: 8080

spring:
  application:
    name: portohost
  datasource:
    url: jdbc:mysql://localhost:3306/portohostdb
    username: username
    password: password
    jpa:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob.non-contextual-creation: true
      properties:
        hibernate:
          show_sql: true
          format_sql: true
    output:
      ansi:
        enabled: Always

logging:
  level:
    com.franciscoabsl: TRACE
    root: INFO
    org:
      hibernate: INFO
      springframework:
        web: DEBUG